### ISSUE TITLE
master branch should upgrade it's version to 0.0.5

### ISSUE THREAD

**Issue by hirokiky** [payjp/payjp-python#16]
I found a commit to bump the version to 0.0.5.
https://github.com/payjp/payjp-python/commit/fb5462cea3a6fda4e2c76c8efd6ebf75ed9d4efc

But it didn't affect to master branch.
https://github.com/payjp/payjp-python/blob/master/setup.py

@satetsu888 can handle this?

**Comment by satetsu888** [comment]
Sorry, my miss operation.
I pushed fb5462c to master branch just now.

Thank you for reporting.
