### ISSUE TITLE
PyPIからバージョン0.0.5のリリースファイルのうち、無意味なものを削除してほしい

### ISSUE THREAD

**Issue by moriyoshi** [payjp/payjp-python#19]

**Comment by moriyoshi** [comment]
## 概要

現在バージョン 0.0.5 でダウンロード可能なファイルのうち、

![image](https://user-images.githubusercontent.com/18755/100833254-eb33ec80-34ac-11eb-8196-ce4641222eba.png)

`payjp-0.0.5.macosx-10.6-intel.tar.gz` はpipでインストールできず、無意味なtarファイルとなっています。

`payjp-0.0.5.tar.gz` が公開されていれば十分ですので、こちらの公開を取り下げていただけないでしょうか。

**Comment by feiz** [comment]
ご報告ありがとうございます。削除しました。
